name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pesde
        uses: ./.github/actions/install-pesde
        with:
          cache: true
          version: v0.6.2+registry.0.2.2
          lune_version: v0.8.9
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Pesde Version
        run: |
          pesde -v

      - name: Check Lune Version
        run: |
          lune -V

      - name: Running Analysis Script
        run: |
          lune run scripts/analyze.luau

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pesde
        uses: ./.github/actions/install-pesde
        with:
          cache: true
          version: v0.6.2+registry.0.2.2
          lune_version: v0.8.9
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Pesde Version
        run: |
          pesde -v

      - name: Check Lune Version
        run: |
          lune -V

      - name: Run Linter
        run: |
          selene src --allow-warnings --quiet

  style:
    name: Check Style
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pesde
        uses: ./.github/actions/install-pesde
        with:
          cache: true
          version: v0.6.2+registry.0.2.2
          lune_version: v0.8.9
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Pesde Version
        run: |
          pesde -v

      - name: Check Lune Version
        run: |
          lune -V

      - name: Run Stylua
        run: |
          selene src --allow-warnings --quiet

  build:
    name: Attempt Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Pesde
        uses: ./.github/actions/install-pesde
        with:
          cache: true
          version: v0.6.2+registry.0.2.2
          lune_version: v0.8.9
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Pesde Version
        run: |
          pesde -v

      - name: Check Lune Version
        run: |
          lune -V

      - name: Run Build Script
        run: |
          lune run scripts/build.luau
